version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: larabook_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=larabook
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - app-network

  db:
    #image: arm64v8/mysql:oracle #Chip ARM
    image: mysql:latest
    container_name: larabook_db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: larabook
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: larabook_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: